### ISSUE TITLE
Realizar Interfaz y programación de APP

### ISSUE THREAD

**Issue by elofr98** [Edu402006/my-first-blog#13]
History User 6

Realizar Interfaz y programación de APP.
designado a @jeanfuentess

**Comment by FelipeFariasG** [comment]
Crear proyecto en vs

**Comment by FelipeFariasG** [comment]
Crear BD

**Comment by FelipeFariasG** [comment]
implementar arquitectura en vs y relacionar con bd

**Comment by FelipeFariasG** [comment]
![image](https://user-images.githubusercontent.com/51409614/136242962-c059d8d4-84e7-4c8a-aad7-ba43cdf4c724.png)
visualización menú principal
