### ISSUE TITLE
Crear APP 

### ISSUE THREAD

**Issue by elofr98** [Edu402006/my-first-blog#15]
History User 7

Crear APP con herramientas estadísticas de ventas. 
designado a @jeanfuentess

**Comment by FelipeFariasG** [comment]
diseñar mejora para estadísticas de venta

**Comment by FelipeFariasG** [comment]
aplicar mejoras en módulos diseñados en issue anterior

**Comment by FelipeFariasG** [comment]
![image](https://user-images.githubusercontent.com/51409614/136243234-3452ba99-5519-4a0e-9630-daf048aaee75.png)
Vista de modulo con estadisticas
