### ISSUE TITLE
Realizar modelo relacional con base de datos

### ISSUE THREAD

**Issue by elofr98** [Edu402006/my-first-blog#16]
History User 7

Realizar modelo relacional con su respectiva base de datos; conectar base de datos con app.
designado a @BenjaVasquez24

**Comment by BenjaVasquez24** [comment]
![Modelo-relacional-1](https://user-images.githubusercontent.com/90570436/136214681-979092eb-2540-44bc-a7f0-9dd5813bef43.jpg)
