### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by Edu402006** [Edu402006/my-first-blog#4]
Realizar el modelo relacional para la base de datos y conectarla

**Comment by elofr98** [comment]
Se a realizado correctamente la base de datos solicitada.

**Comment by hipo21** [comment]
![WhatsApp Image 2021-10-06 at 04 37 07](https://user-images.githubusercontent.com/91704328/136132516-673a3936-b42d-49f5-a484-df88416ddaf6.jpeg)
Modelo Relacional del inventario realizado correctamente
