### ISSUE TITLE
Crear modelo relacional de base de datos

### ISSUE THREAD

**Issue by elofr98** [Edu402006/my-first-blog#6]
History User 1
Crear modelo relacional de base de datos, designado a @hipo21

**Comment by hipo21** [comment]
![WhatsApp Image 2021-10-06 at 04 37 07](https://user-images.githubusercontent.com/91704328/136132636-fbd1b2c2-0fa7-4e67-8774-7add2ce5b458.jpeg)
Modelo Relacional del Inventario realizado correctamente.
