### ISSUE TITLE
Realizar modelo relacional y base de datos

### ISSUE THREAD

**Issue by elofr98** [Edu402006/my-first-blog#9]
History User 4

Realizar modelo relacional y base de datos.
designado a @hipo21

**Comment by hipo21** [comment]
![WhatsApp Image 2021-10-06 at 04 37 07 (2)](https://user-images.githubusercontent.com/91704328/136133034-4d0c3a61-cd4f-4992-8965-79d5653b1417.jpeg)
Modelo Relacional del sistema de pago de facturas realizada correctamente
